### ISSUE TITLE
Nova Markdown field preview fails

### ISSUE THREAD

**Issue by piotrku** [spatie/nova-translatable#103]
The XHR error returned is 404

```
POST http://site.test/nova-api/posts/field/translations_content_ar/preview?editing=true&editMode=update
[HTTP/1.1 404 Not Found 230ms]
```

I works fine on non translatable fields like:
```
http://site.test/nova-api/news/field/intro/preview?editing=true&editMode=update
```

And returns 404 on a translatable field `content` - the original query is (notice the transformed fieldname `translations_content_en`):
```
http://site.test/nova-api/posts/field/translations_content_en/preview?editing=true&editMode=update
```

But I tested different URLs for this field - none works:
```
http://site.test/nova-api/posts/field/translations_content/preview?editing=true&editMode=update
http://site.test/nova-api/posts/field/content_en/preview?editing=true&editMode=update
http://site.test/nova-api/posts/field/content/preview?editing=true&editMode=update
```

**Comment by dariusmb** [comment]
Hello. We are encountering the same issue where the preview of Markdown fields does not work after updating from Nova 3 to Nova 4. Is there any fix available for this issue?

**Comment by chimit** [comment]
This issue still takes place. Please, reopen it, @freekmurze

**Comment by ugurdnlr** [comment]
Hi, i have same issue. is there any solution for this ?

**Comment by RRosalia** [comment]
??

**Comment by xdubois** [comment]
Same issue
